config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :subjects

    root to: "static_pages#home"
  end
  resources :users, only: [:show]
  resources :courses, only: [:show]

  root to: "static_pages#home"
  match "/home" => "static_pages#home", via: :get
  match "/signin" => "sessions#new", via: :get
  match "/signin" => "sessions#create", via: :post
  match "/signout" => "sessions#destroy", via: :delete
end

app/models/course.rb
class Course < ActiveRecord::Base
	
end

app/models/course_subject.rb
class CourseSubject < ActiveRecord::Base
	belongs_to :course
	belongs_to :subject
end

app/models/course_subject_task.rb
class CourseSubjectTask < ActiveRecord::Base
end

app/models/course_user.rb
class CourseUser < ActiveRecord::Base
	has_many :user
	has_many :course
	
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :tasks
  accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: proc {|attributes| attributes["name"].blank?}
  validates :name, :content, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :subject
  has_many :course_subject_tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessor :no_password_validation

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: {maximum:30, minimum: 6}
  validates :email, presence: true, format: {with: EMAIL_REGEX}, uniqueness: true
  validates :password, length:{minimum:6}, unless: :no_password_validation

  before_create :create_remember_token
  before_save {|user|
    user.email = email.downcase
  }

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/models/user_subject.rb
class UserSubject < ActiveRecord::Base
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < ApplicationController
  before_action :signed_in_admin
  layout "layouts/admin"
  def home
  end
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_admin
  layout "layouts/admin"

  def index
    @subjects = Subject.paginate page: params[:page], per_page: 15
  end

  def show
  end

  def new
    @subject = Subject.new
  end

  def edit
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      redirect_to [:admin, @subject], notice: "Subject was successfully created."
    else
      render :new
    end
  end

  def update
    if @subject.update_attributes subject_params
      redirect_to [:admin, @subject], notice: "Subject was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @subject.destroy
    redirect_to admin_subjects_path, notice: "Subject was successfully destroyed."
  end

  private
    def set_subject
      @subject = Subject.find params[:id]
    end

    def subject_params
      params.require(:subject).permit(:name,:content, tasks_attributes: [:name])
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :signed_in_admin
  layout "layouts/admin"

  def index
    @users = User.paginate page: params[:page], per_page: 15
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Successfully created user"
      redirect_to [:admin, @user]
    else
      flash[:error] = "Unsuccessfully created user"
      render :new
    end
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = "Successfully updated user"
      redirect_to [:admin, @user]
    else
      flash[:error] = "Unsuccessfully updated user"
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "Successfully deleted user"
    redirect_to admin_users_path
  end

  private
  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:name, :email, :password_digest, :remember_token, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :signed_in_user

  def show
  	@course = Course.find_by id: params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render layout: false
  end

  def create
    user = User.find_by_email params[:email]
    remember = params[:remember]
    if user && user.authenticate(params[:password])
      sign_in user,remember
      redirect_back
    else
      flash[:error] = 'Invalid Email/Password combination'
      render 'sessions/new'
    end
  end

  def destroy
    sign_out
    redirect_to signin_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :signed_in_user
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user

  def show
  end

  private
    def set_user
      @user = User.find params[:id]
    end

    def user_params
      params.require(:user).permit(:name, :email, :remember_token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Framgia E-Learning System"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  include UsersHelper
  def sign_in user, remember = false
    remember_token = SecureRandom.urlsafe_base64
    cookies.permanent[:remember_token] ={
        value: remember_token,
        expires: remember ? 2.weeks.from_now : nil
    }
    user.no_password_validation = true
    user.update_attributes remember_token: remember_token
    user.no_password_validation = false
    @current_user = user
  end

  def sign_out
    current_user = nil
    cookies.delete :remember_token
  end

  def current_user user
    self.current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token cookies[:remember_token]
  end

  def correct_user? user
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    redirect_to signin_path, notice: "Please sign in" unless signed_in?
  end

  def signed_in_admin
    redirect_to root_path, notice: "You do not have permission" unless current_user.admin?
  end

  def redirect_back
    if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to :back
    else
      redirect_to root_url
    end
  end

  def redirect_back_or default
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user,options={size:100})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size];
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/admin/subjects/_form.html.erb
<%= form_for [:admin, @subject] do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class:"input-block-level" %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content, class:"input-block-level", rows: 10 %>
    </div>
    <h3>Task: </h3>
    <div id="FormTask">
        <%= link_to "Add new task", "#", class: "TaskAdd" %>
        <%= f.fields_for :tasks do |task_builder| %>
            <div class="field">
                <%= task_builder.text_field :name %>
                <%= task_builder.hidden_field :_destroy %>
                <%= link_to "Remove", "#", class: "TaskRemove" %>
            </div>
        <% end %>
    </div>
    <div class="actions">
      <br>
    <%= f.submit %>
    </div>
<% end %>

<script type="text/javascript">
    $("#FormTask .TaskAdd").on("click", function(){
        event.preventDefault();
        var i = $("#FormTask").children(".field").length;
        var field = $("<div />").addClass("field");
        field.append($("<input type='text' />").attr("name","subject[tasks_attributes]["+i+"][name]"))
             .append($("<input type='hidden' />").attr("name","subject[tasks_attributes]["+i+"][_destroy]"))
             .append($("<a />").html("Remove").addClass("TaskRemove").attr("href","#")
                               .bind("click",function(){
                                    event.preventDefault();
                                    $(this).prev().val(1).prev().attr("disabled","disabled")
                                }));
        $("#FormTask").append(field);
    });
    $("#FormTask .TaskRemove").on("click",function(){
        event.preventDefault();
        if ($(this).hasClass("undo"))
            $(this).html("Remove").removeClass("undo").prev().val(0).prev().removeAttr("disabled")
        else
            $(this).html("Undo").addClass("undo").prev().val(1).prev().attr("disabled","disabled")
    })
</script>

app/views/admin/subjects/edit.html.erb
<div class="container">
  <h1>Editing subject</h1>
  <%= render "form" %>
  <%= link_to "Show", [:admin, @subject] %> |
  <%= link_to "Back", admin_subjects_path %>
</div>

app/views/admin/subjects/index.html.erb
<div class="container">
    <h1>Listing subjects</h1>
    <table>
      <thead>
        <tr>
          <th width="300">Name</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @subjects.each do |subject| %>
          <tr>
            <td>subject.name</td>
            <td><%= link_to "Show", [:admin, subject] %>|
            <%= link_to "Edit", edit_admin_subject_path(subject) %>|
            <%= link_to "Destroy", [:admin, subject], method: :delete, data: { confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to "New Subject", new_admin_subject_path %>
</div>

app/views/admin/subjects/new.html.erb
<div class="container">
  <h1>New subject</h1>
  <%= render "form" %>
  <%= link_to "Back", admin_subjects_path %>
</div>

app/views/admin/subjects/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>
    <%= @subject.name %>
  </h1>
  <div class="col-md-6">
    <p>
      <%= @subject.content %>
    </p>
  </div>
  <div class="col-md-6">
    <h4>Tasks: </h4>
    <ol>
    <% @subject.tasks.each do |task| %>
        <li><%= task.name %></li>
    <% end %>
    </ol>
  </div>
  <%= link_to "Edit", edit_admin_subject_path(@subject) %> |
  <%= link_to "Back", admin_subjects_path %>
</div>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], class:"form-signin" do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class:"input-block-level" %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email, class:"input-block-level" %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password, class:"input-block-level" %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, class:"input-block-level" %>
    </div>
    <div class="field">
      <%= f.check_box :admin %>
      <%= f.label :admin %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/admin/users/edit.html.erb
<% provide(:title, "Edit member") %>
<div class="container">
  <%= render "form" %>
</div>

app/views/admin/users/index.html.erb
<% provide(:title,"Memebers") %>

<div class="container">
  <h3>Members</h3>
  <%= link_to "Create new member", new_admin_user_path %>
  <div class="row">
    <%= will_paginate @users %>
    <table class="table table-striped table-bordered table-hover">
      <thead>
          <tr>
            <th width="200">Name</th>
            <th>Email</th>
            <th width="150">Course</th>
            <th width="160">Action</th>
          </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td>&nbsp;</td>
            <td>
              <%= link_to "Show", [:admin, user] %> |&nbsp;
              <%= link_to "Edit", edit_admin_user_path(user) %> |&nbsp;
              <%= link_to "Destroy", [:admin, user], method: :delete %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @users %>
  </div>
</div>

app/views/admin/users/new.html.erb
<% provide(:title, "Sign Up") %>
<div class="container">
  <%= render "form" %>
</div>

app/views/admin/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="container">
    <div class="row">
      <aside class="col-md-4">
        <section>
          <h1>
            <%= gravatar_for @user,:size=>"100" %>
            <%= @user.name %>
          </h1>
        </section>

      </aside>
      <div class="col-md-8">

      </div>r
    </div>
    <%= link_to "Edit", edit_admin_user_path(@user) %> |
    <%= link_to "Back", admin_users_path %>
</div>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>
<p>Find me in app/views/courses/show.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Remember token:</strong>
  <%= @user.remember_token %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>